# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 637b16c4bce049aa3583c4732d32087b07a8e94f203785b78ce34a3b5540606bacc0ed48e6eedb099eb0e0d48cf22cac4b433fae4cd82f782abb37a5e3b1df39

test:
  secret_key_base: fcb2fa2c52708a4e4c2293a325d8780992df906d680d8040a5285c159cdfda10221b5d2d8794ddda95769d2da98d36660bee7c844d864f95b2867fbe416f9804

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
